type = Type.create(name: 'Bread')
item = Item.create(name: 'Bread', type_id: type.id)
price = Price.create(date_bought: 20150804, amount: 12.50, item_id: item.id)
item = Item.create(name: 'Rolls', type_id: type.id)
item = Item.create(name: 'Wraps', type_id: type.id)
item = Item.create(name: 'Ricecakes', type_id: type.id)
price = Price.create(date_bought: 20150804, amount: 20, item_id: item.id)

type = Type.create(name: 'Dairy')
item = Item.create(name: 'Milk', type_id: type.id)
price = Price.create(date_bought: 20150801, amount: 26, item_id: item.id)
price = Price.create(date_bought: 20150803, amount: 26, item_id: item.id)
item = Item.create(name: 'Butter', type_id: type.id)
item = Item.create(name: 'Cheese', type_id: type.id)
item = Item.create(name: 'Yoghurt', type_id: type.id)

type = Type.create(name: 'Cereal')
item = Item.create(name: 'All Bran', type_id: type.id)
item = Item.create(name: 'Rice Krispies', type_id: type.id)
item = Item.create(name: 'Weetbix', type_id: type.id)
price = Price.create(date_bought: 20150804, amount: 39.90, item_id: item.id)
item = Item.create(name: 'Oatpops', type_id: type.id)
item = Item.create(name: 'Pronutro', type_id: type.id)
price = Price.create(date_bought: 20150804, amount: 25, item_id: item.id)

type = Type.create(name: 'Drinks')
item = Item.create(name: 'Coffee', type_id: type.id)
item = Item.create(name: 'Hot Chocolate', type_id: type.id)
item = Item.create(name: 'Tea', type_id: type.id)
price = Price.create(date_bought: 20150802, amount: 61, item_id: item.id)
item = Item.create(name: 'Juice', type_id: type.id)

type = Type.create(name: 'Fruit and Vegetables')
item = Item.create(name: 'Apples', type_id: type.id)
item = Item.create(name: 'Bananas', type_id: type.id)
item = Item.create(name: 'Clementines', type_id: type.id)
item = Item.create(name: 'Grapes', type_id: type.id)
item = Item.create(name: 'Butternut', type_id: type.id)
item = Item.create(name: 'Potatoes', type_id: type.id)
price = Price.create(date_bought: 20150803, amount: 24, item_id: item.id)
item = Item.create(name: 'Lemons', type_id: type.id)
item = Item.create(name: 'Oranges', type_id: type.id)
item = Item.create(name: 'Carrots', type_id: type.id)
item = Item.create(name: 'Leeks', type_id: type.id)
item = Item.create(name: 'Lettuce', type_id: type.id)
price = Price.create(date_bought: 20150801, amount: 14, item_id: item.id)
item = Item.create(name: 'Spinach', type_id: type.id)
item = Item.create(name: 'Sweet Potatoes', type_id: type.id)
item = Item.create(name: 'Tomatoes', type_id: type.id)
price = Price.create(date_bought: 20150803, amount: 15, item_id: item.id)
item = Item.create(name: 'Peas', type_id: type.id)
item = Item.create(name: 'Pineapple', type_id: type.id)
item = Item.create(name: 'Onions', type_id: type.id)

type = Type.create(name: 'Meat')
item = Item.create(name: 'Beef', type_id: type.id)
item = Item.create(name: 'Biltong', type_id: type.id)
item = Item.create(name: 'Chicken', type_id: type.id)
price = Price.create(date_bought: 20150803, amount: 62.30, item_id: item.id)
item = Item.create(name: 'Fish', type_id: type.id)
item = Item.create(name: 'Ham', type_id: type.id)
item = Item.create(name: 'Tuna', type_id: type.id)

type = Type.create(name: 'Spread')
item = Item.create(name: 'Honey', type_id: type.id)
item = Item.create(name: 'Marmite', type_id: type.id)
item = Item.create(name: 'Jam', type_id: type.id)
price = Price.create(date_bought: 20150803, amount: 32, item_id: item.id)
item = Item.create(name: 'Peanut Butter', type_id: type.id)

type = Type.create(name: 'Other')
item = Item.create(name: 'Flour', type_id: type.id)
item = Item.create(name: 'Oil', type_id: type.id)
item = Item.create(name: 'Sugar', type_id: type.id)
item = Item.create(name: 'Pasta', type_id: type.id)
item = Item.create(name: 'Raisins', type_id: type.id)
item = Item.create(name: 'Rice', type_id: type.id)
item = Item.create(name: 'Tinned Tomatoes', type_id: type.id)
item = Item.create(name: 'Mayonnaise', type_id: type.id)

type = Type.create(name: 'Sweets')
item = Item.create(name: 'Jelly Beans', type_id: type.id)
item = Item.create(name: 'Chocolate', type_id: type.id)
item = Item.create(name: 'Chips', type_id: type.id)
price = Price.create(date_bought: 20150803, amount: 28, item_id: item.id)
item = Item.create(name: 'Ice Cream', type_id: type.id)
item = Item.create(name: 'Biscuits', type_id: type.id)

type = Type.create(name: 'Eggs')
item = Item.create(name: 'Eggs', type_id: type.id)

type = Type.create(name: 'Dog Food')
item = Item.create(name: 'Dog Biscuits', type_id: type.id)
item = Item.create(name: 'Dog Meat', type_id: type.id)
